### ISSUE TITLE
fix(agent): make run cancellation deterministic across tool and model boundaries

### ISSUE THREAD

**Issue by chesterlincoln** [zhnt/loushang#305]
## Problem

The Agent loop has a reproducible cancellation race at the boundary between a completed tool call and the next model call.

The scenario `tool_result_then_abort_then_new_prompt` expects model inputs:

```text
["use tool", "你好"]
```

but on Python 3.11 it can observe:

```text
["use tool", "use tool", "你好"]
```

The completed tool result is returned, the abort controller has not yet been scheduled, and the Agent loop starts another provider call with the previous prompt before the abort request becomes visible.

This was exposed while validating #303, but it is not introduced by #303: the same failure is reproducible on `main` under Python 3.11.15. The same test passing under Python 3.14 is further evidence that the current behavior depends on event-loop scheduling rather than a deterministic cancellation contract.

## Reproduction

```bash
uv run pytest \
  'tests/agent/test_agent_loop_scenarios.py::test_agent_loop_control_flow_scenarios[tool_result_then_abort_then_new_prompt]' \
  -q
```

Full-suite state when diagnosed:

```text
5575 passed, 8 skipped, 1 failed
```

The only failure was the scenario above.

## Current behavior and root cause

This is not a missing boolean check at one line. Several lifecycle decisions are currently split across layers:

- `loushang.agent.AbortSignal` is only a mutable `aborted: bool`; it is not waitable and has no atomic cancellation/checkpoint operation.
- `Agent.abort()` sets that boolean and separately schedules forced task cancellation after 50 ms.
- `agent_loop.py` polls the boolean at several boundaries. After a tool finishes, the loop can pass the check, drain an empty steering queue, and begin the next provider call without giving an already-runnable abort caller a deterministic publication point.
- The AI provider layer already accepts a structural cancellation signal with `is_cancelled()` and `wait()`; the Agent token does not implement it, so provider cancellation falls back to polling.
- Abort terminalization is split between the normal loop abort path and `Agent._handle_run_failure()`, creating competing ways to append an aborted assistant message and emit terminal events.
- Queue clearing is a separate call from `abort()`, so cancellation and the disposition of steering/follow-up messages are not atomic.
- Events carry no run identity, so a force-cancelled or slow old operation has no general fence preventing late events from mutating a newer run.

A local `await asyncio.sleep(0)` after tool execution can make this scenario green, but it does not define or enforce the cancellation semantics and must not be considered the complete fix.

## Target contract

Implement a first-class, per-run cancellation scope owned by `loushang.agent`.

### 1. Waitable, monotonic cancellation token

The read-only token passed to providers, tools, hooks, and listeners should provide:

- `is_cancelled()`
- `wait()`
- a cancellation checkpoint / `raise_if_cancelled()`
- cancellation reason/source metadata where useful
- compatibility with the existing `.aborted` read during migration

Only the owning controller/run scope may transition it, and cancellation must be idempotent and monotonic.

### 2. One authoritative run scope

Replace independently managed active task/controller state with one run lifecycle object containing at least:

- run identity/generation
- cancellation controller/token
- active task
- current phase
- terminalization guard
- force-cancel fallback handle

A new prompt must always receive a new scope and token. State from an aborted run must never be reused.

### 3. Deterministic cancellation gates

Define semantic checkpoints at every boundary before starting new external or irreversible work:

- before the first and every subsequent provider call
- before each tool prepare/execute phase
- after tool completion/finalization and before the next model iteration
- before consuming steering/follow-up messages
- during retry/backoff and compaction waits

Long-running provider/tool work should be raced against the token's wait operation. A cooperative scheduler handoff may be an implementation detail of a checkpoint, but scattered sleeps are not the contract.

Core invariant:

> Once cancellation is committed for run N, no new provider call, tool call, queue consumption, or transcript mutation may begin for run N.

### 4. Exactly-once terminalization

Choose one owner for closing a run. An aborted run must produce a coherent terminal projection exactly once:

- no duplicate aborted assistant messages
- no duplicate `turn_end` or `agent_end`
- `stop_reason == "aborted"`
- streaming and pending-tool state cleared exactly once
- forced `Task.cancel()` is only a cleanup fallback and does not independently decide transcript semantics

### 5. Explicit transcript and queue policies

Define and test these policies instead of relying on timing:

- a tool result completed before cancellation is preserved in the transcript
- an unfinished tool call receives one explicit policy (aborted result or omission), consistently for sequential and parallel execution
- abort and queue disposition are one Agent operation; steering and follow-up queues may have distinct documented policies
- a prompt submitted after `wait_for_idle()` starts a clean run and cannot consume stale work from the aborted run

### 6. Stale-event fencing

Associate emitted/processed events with the run identity, at least internally. Events from a superseded or terminal run must be ignored or diagnosed and must not mutate the active run's:

- messages
- streaming message
- pending tool calls
- error state
- UI/session projection

### 7. Cross-layer integration

- `loushang.agent` owns run cancellation lifecycle and invariants.
- `loushang.ai` consumes the structural waitable token; it does not own Agent lifecycle.
- tools and hooks receive the same per-run token.
- Coding retry/compaction wait paths should consume the same waitable contract instead of independent 50 ms polling.
- Unrelated short-lived UI completion cancellation tokens are out of scope unless a concrete coupling is found.

### Behavioral invariants

- [ ] No provider call starts after cancellation has been committed for that run.
- [ ] No tool call starts after cancellation has been committed for that run.
- [ ] A tool result completed before cancellation is persisted once.
- [ ] Aborted transcript message and terminal events are emitted exactly once.
- [ ] Pending tool and streaming state are empty after `wait_for_idle()`.
- [ ] Double abort and abort-while-idle are idempotent.
- [ ] A new prompt after abort uses a fresh run and cannot receive late events from the old run.
- [ ] Queue retention/clearing follows an explicit tested policy.

### Deterministic test matrix

Use barriers/events, not timing sleeps, for at least:

- [ ] abort before first provider call
- [ ] abort during provider stream
- [ ] abort after assistant response and before tool execution
- [ ] abort while a tool is running
- [ ] abort after tool completion and before the next provider call
- [ ] sequential and parallel tool batches
- [ ] before/after tool hooks
- [ ] provider retry/backoff
- [ ] steering and follow-up queues
- [ ] provider/tool that ignores cooperative cancellation and requires forced cleanup
- [ ] stale late event from an old run
- [ ] double abort, abort while idle, abort then new prompt

Run the relevant matrix on the supported Python versions, including 3.11 and 3.14, followed by the full test and example suites.

## Suggested delivery sequence

1. Introduce the waitable token/run-scope contract with compatibility for `.aborted`, plus invariant tests.
2. Consolidate Agent lifecycle and exactly-once terminalization.
3. Add deterministic phase gates and provider/tool cancellation races.
4. Make queue policy atomic and add run-identity stale-event fencing.
5. Migrate Coding retry/compaction consumers off polling, remove compatibility paths, and run full validation.

This should be delivered as a dedicated Agent-runtime change rather than folded into #303.

---

### 问题现象

Agent 在工具调用已经完成、准备发起下一次模型调用的边界上存在异步调度竞态。

失败场景中，用户先发送 `use tool`，工具返回后立即执行 Abort，然后再发送新提示词 `你好`。预期模型只收到：

```text
["use tool", "你好"]
```

实际在 Python 3.11 环境可能变成：

```text
["use tool", "use tool", "你好"]
```

也就是工具已经返回，但 Abort 真正生效之前，旧请求又调用了一次模型。

该问题是在验证 PR #303 时暴露的，但不是 PR #303 新引入的回归：相同的 `main` 提交在 Python 3.11.15 可以稳定复现，而在 Python 3.14 恰好通过。这说明结果受事件循环调度顺序影响，当前取消语义并不确定。

### 根本原因

这不是某一行少写了一次 `if aborted`，而是一次 Agent run 的取消所有权和终结责任分散在多个位置：

- `AbortSignal` 只有一个可变布尔值，不能等待取消、不能形成原子的取消检查点。
- `Agent.abort()` 先修改布尔值，再单独安排 50ms 后的强制任务取消，两者不是统一生命周期。
- Agent loop 只在若干位置轮询布尔值；工具完成后可以在 Abort 调用方获得调度机会之前直接开始下一次 provider 调用。
- AI provider 已支持 `is_cancelled()` / `wait()` 形式的结构化取消协议，但 Agent 传入的弱令牌无法直接满足，因此退化为轮询。
- 正常循环与 `Agent._handle_run_failure()` 都可能负责生成 aborted 消息和终结事件，存在重复终结的风险。
- Abort 与 steering/follow-up 队列清理是两个独立操作，不能原子地决定队列保留策略。
- 事件没有 run identity；旧 run 被强制取消后产生的迟到事件，缺少通用隔离机制，理论上可能污染新 run。

在工具执行后加入 `await asyncio.sleep(0)` 可以让当前测试变绿，但它只改变调度概率，没有建立完整取消契约，因此不能作为最终方案。

### 完整修复目标

取消语义应由 `loushang.agent` 统一拥有，并为每一次 run 建立独立的 cancellation scope：

1. 提供可等待、单向且幂等的取消令牌，至少支持 `is_cancelled()`、`wait()` 和统一 checkpoint。
2. 用一个 run scope 统一持有 run id、取消控制器、运行任务、阶段、终结保护和强制取消回退，不再分别维护容易失配的状态。
3. 在每次 provider 调用、工具准备/执行、工具结束到下一轮模型调用、队列消费、重试和 compaction 等边界建立确定性的取消门禁。
4. 由唯一终结路径生成 aborted transcript 和 `turn_end` / `agent_end`，确保 exactly-once。
5. 明确 transcript 策略：取消前已经完成的工具结果必须保留；未完成工具的表示方式需要统一；取消与队列处置必须成为同一个原子操作。
6. 为 run 增加 identity/generation 隔离，旧 run 的迟到 provider、tool 或 listener 事件不得修改新 run 状态。
7. AI provider、工具、hooks、Coding retry/compaction 共同消费同一个可等待取消协议，但 Agent 生命周期仍只由 `loushang.agent` 负责。

核心不变量是：

> run N 的取消一旦提交，run N 不得再开始新的 provider 调用、工具调用、队列消费或 transcript 写入。

### 影响范围

直接影响 Agent loop、Agent 生命周期、工具执行、provider 取消传播、steering/follow-up 队列和 Coding 层的 retry/compaction 等待。它不是单个测试夹具问题，也不应扩展成所有 UI 临时取消令牌的无差别统一；修复边界是一条完整的 Agent run cancellation 纵向链路。

### 验收重点

- Abort 提交后旧 run 不再开始新的模型或工具调用。
- Abort 消息、`turn_end` 和 `agent_end` 各自只产生一次。
- 取消前已完成的工具结果只保存一次。
- `wait_for_idle()` 后 streaming 和 pending tool 状态全部清空。
- double abort、idle abort、abort 后新 prompt 都具备确定行为。
- 旧 run 的迟到事件不会污染新 run。
- 使用事件/barrier 构造确定性测试，不依赖 sleep 调时序。
- Python 3.11 与 3.14 均通过目标场景，并完成全量 tests 和 examples 验证。

**Comment by zhnt** [comment]
已按“最小改动、先固定真实语义边界”的方向完成本地修正。此次没有修改生产 Agent loop，也没有加入 asyncio.sleep(0)。

进一步核对后，当前复现有两个关键问题：

1. 场景里的 ToolFinished 是 ScenarioTool.execute() 在返回 AgentToolResult 之前设置的内部 checkpoint，并不是 Agent 对外发布的 tool_execution_end。
2. ScenarioRuntime.wait_for() 使用 asyncio.wait_for(event.wait())。Python 3.11 会为 event.wait() 引入中间 Task；工具 Task 完成、Agent loop 恢复、外部场景 Task 恢复三者的排队顺序因此与 Python 3.14 不同。

所以当前失败证明的是测试夹具依赖 asyncio.wait_for 的实现调度，而不是已经证明生产事件边界违反取消契约。为避免让生产代码配合测试调度，本次修改为：

- ToolFinished 只在公开 tool_execution_end 事件被 listener 处理时发布，不再由工具内部提前发布。
- 新增一次性 AbortOnToolFinished 场景步骤，在 tool_execution_end listener 的同步分发过程中调用 Agent.abort()。
- ScenarioRuntime.wait_for() 改用 Python 3.11+ 的 asyncio.timeout() + 直接 await Event.wait()，移除 wait_for 的中间 Task。
- 增加 transcript roles 断言，确认取消前已经发布的 ToolResultMessage 被保留，并且只产生一个 aborted boundary。
- 保持原断言：旧 run 不会再开始第二次 provider call，abort 后的新 prompt 使用干净的新 run。

验证结果：

- Python 3.11.15：tests/agent/test_agent_loop_scenarios.py，11 passed
- Python 3.11.15：tests/agent，134 passed
- Python 3.14.4：tests/agent，134 passed
- Ruff：All checks passed
- git diff --check：通过

结论：#305 当前的精确复现可以通过修正测试语义和测试调度消除，不需要为它引入完整 ActiveRun/generation/统一 terminalization 重构。issue 正文中提出的 waitable token、stale-event fencing、未完成工具结果策略等仍可作为独立的 Agent runtime hardening 工作，但不应由这个受 wait_for 调度影响的场景直接推出，也不建议在同一修复中扩大范围。
